### PR TITLE
xbuild: `--sysroot` link arg is already set by `fn set_sysroot()`

### PR DESCRIPTION
**Pull request by MarijnS95**

### CODE REVIEW

**Review by dvc94ch — APPROVED** [review]

**Comment by dvc94ch** [comment]
yeah, those are github secrets that don't apply to forks

**Comment by MarijnS95** [comment]
@dvc94ch Should those CI steps perhaps be skipped when not having access to secretes?

**Comment by dvc94ch** [comment]
Do you know how to do that? But that would be great

**Comment by MarijnS95** [comment]
You can simply add `if:` to `jobs` and individual `steps`, but I'm not sure what predicate to use here. We can check for `{{ organization/owner == 'cloudpeers' }}`, or if possible even better: check if the required secret is set/available? Someone will need to go through the GH docs and test some of these out :)

**Comment by dvc94ch** [comment]
for now you can push to a branch here, you have write access. would be helpful to namespace your branch so you can use a branch called  "marijn/sysroot" to open a PR.

**Pull request merged**
