### PR TITLE
No flutter

### PR DESCRIPTION
**Pull request by dvc94ch**
@MarijnS95 wdyt?

### CODE REVIEW

**Comment by MarijnS95** [comment]
It looks like this is a combination of removing flutter, bumping crates and fixing incompatibilities, cleaning up code, refactoring code, and maybe even adding a new feature or two somewhere?

**Comment by dvc94ch** [comment]
Will fix ci once I'm done with the refocusing.

**Comment by MarijnS95** [comment]
Ack. Think I'll just build test my apps with the changes you're making then. No way I can review the contents of this PR unless you split it up into smaller chunks :)

**Comment by dvc94ch** [comment]
While it should work to build any iOS/android app, https://dioxuslabs.com/ will be officially supported. Got it working on iOS yesterday and will update the README once I get it working on android

**Comment by MarijnS95** [comment]
Heh, another UI framework :)

**Comment by dvc94ch** [comment]
Well it's the first that works on mobile and seems closer to production ready than any other rust UI framework

**Comment by MarijnS95** [comment]
That's cool, I'll keep it in mind. Have so far only ever "needed" / used imgui, never built a Rust app with "normal" UI but that might happen some day :)

**Pull request merged**
